### ISSUE TITLE
Q: Do you support default values of properties?

### ISSUE THREAD

**Issue by blipinsk** [MarcinMoskala/generate-builder#1]
When I was building https://github.com/blipinsk/data-class-builder, the limited information about default values was very restrictive in what I could generate.
Do you support default values of properties? And if yes, how do you "intercept" the default value of the property (or how do you work around the lack of the value)?

**Comment by MarcinMoskala** [comment]
No, apparently it is currently impossible as those are expressions (not values). They are not present in the metadata. With some effort, it might be possible to create an object using those default values (using generated syntactic constructors) but it would be hard and probably Kotlin version-specific. 

I don't need this feature for now as these builders are primarily to create objects for unit tests that are written in Groovy or other JVM language. Default values there are generally different than in src.

**Comment by MarcinMoskala** [comment]
BDW I just had your article open: https://medium.com/the-fabulous/kotlin-extension-methods-generation-15b5e6499dc8
I like it a lot.

**Comment by blipinsk** [comment]
> I don't need this feature for now as these builders are primarily to create objects for unit tests that are written in Groovy or other JVM language. Default values there are generally different than in src.

Ok, got that. Thanks for explaining.

> No, apparently it is currently impossible as those are expressions (not values). They are not present in the metadata.

Yea that was my findings as well. I had to flex my brain to work around that 😆 

> BDW I just had your article open: https://medium.com/the-fabulous/kotlin-extension-methods-generation-15b5e6499dc8
I like it a lot.

Thank you! I need to tackle another big subject like that... 🤔 😊
